version: '3'
services:
  twitter-scraper:
    image: twitter-scraper:latest
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./crawler.py:/app/crawler.py
    environment:
    - TWITTER_BEARER=XX
    - BATCH_SIZE=100
    - TOT_TWEET=1000
    entrypoint: ["python3",  "/app/crawler.py"]
