apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-screaper
  namespace: mynamespace-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-screaper
  template:
    metadata:
      labels:
        app: twitter-screaper
    spec:
      volumes:
        - name: data
      containers:
        - name: twitter-screaper
        image: simopatu/twitter-screaper
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        volumeMounts:
          - name: data
            mountPath: /data
