apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-screaper
  namespace: mykube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-screaper
  template:
    metadata:
      labels:
        app: my-screaper
    spec:
      containers:
      - name: my-screaper
        image: simopatu/my-screaper
        imagePullPolicy: Always
        ports:
        - containerPort: 80
